### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by MathieuLorber**
Most important dependencies updated.
I mainly need a most recent okhttp.

### CODE REVIEW

**Comment by pbassut** [comment]
Did that even compile? retrofit2 does not include retrofit.client.Client anymore. And we rely on it here: https://github.com/segmentio/analytics-java/blob/0ed8f41931018679063263e53ec48968a9bcda43/analytics/src/main/java/com/segment/analytics/Analytics.java#L22

**Comment by pbassut** [comment]
make sure you `mvn dependency:purge-local-repository` before running it again

**Comment by MathieuLorber** [comment]
I just built it in an empty container.
retrofit.client.Client comes with com.jakewharton.retrofit:retrofit1-okhttp3-client. But right now I'm not sure / don't remember if this one is supposed to be used with retrofit 2

**Comment by pbassut** [comment]
https://github.com/square/retrofit/issues/1124
Help me understand: you're also upgrading retrofit 1 to retrofit 2, correct?

**Comment by MathieuLorber** [comment]
Don't really remember, but the diff is clear : i did. I clearly didn't realize the impact at the moment.

I'm gonna take a look but honestly I'm not an expert of retrofit (it's okhttp which interested me), I don't think I'll be the better person to make a clean upgrade.

**Comment by pbassut** [comment]
Ok. We'll be closing this since there's already two retrofit2 PRs(which will probably be combined into one) in course ([here](https://github.com/segmentio/analytics-java/pull/174) and [here](https://github.com/segmentio/analytics-java/pull/148)

**Pull request closed without merging**
