### PR TITLE
fix: AnalyticsClient Looper won't start if isShutdown is true

### PR DESCRIPTION
**Pull request by itsdebs**
AnalyticsClient was starting a looper even if isShutdown was true when initialising.
In that case messages submitted to Analytics were flushed even if AnalyticsClient was initialised with isShutdown as true.

### CODE REVIEW

**Comment by jorgen25** [comment]
Could we do something about the commit checks??  i see these failed
ci/circleci: test 
ci/circleci: test-jdk11 
ci/circleci: test-jdk8 
ci/circleci: test-jdklatest

**Review by jorgen25 — CHANGES_REQUESTED** [review]
Could we do something about the commit checks?? i see these failed
ci/circleci: test
ci/circleci: test-jdk11
ci/circleci: test-jdk8
ci/circleci: test-jdklatest

**Comment by itsdebs** [comment]
Sure. @jorgen25 I need to make a few changes to test cases about the mock.

**Comment by itsdebs** [comment]
@jorgen25 Will it be possible for me to check which test cases are failing and the test reports? That would be very helpful

**Comment by itsdebs** [comment]
@jorgen25 Tests have passed now. They were mainly formatting issues by spotless.

**Comment by nd4p90x** [comment]
Replaced by PR #323 Thank you

**Pull request closed without merging**
