### PR TITLE
Use OkHttp 3 as the default client.

### LINKED ISSUE #105: upgrade okhttp version?
Right now you are using `okhttp` version `2.2.0` which is 3 years old. I'm having issues using this library because it's using such an old version of `okhttp` and some of my other libraries that use `okhttp` use a newer version and the transitive dependency between them `okio` has API breaking changes. It would be awesome if you could upgrade to `okhttp` version `3.6.0` or later.

### PR DESCRIPTION
**Pull request by f2prateek**
Closes #105

### CODE REVIEW

**Comment by greenkiwi** [comment]
@f2prateek I see that it appears you are preparing for another development [cycle](https://github.com/segmentio/analytics-java/commit/83f6ff7567c6d377b12ccdba5d928f077402db41).  Will this PR make it into that cycle?

We have some libraries that use retrofit 2.3, so we would really like to remove the old okhttp references.

**Comment by f2prateek** [comment]
@greenkiwi Likely not; we just released 2.1.0.

If you need okhttp 3, you can set the client on the library https://github.com/segmentio/analytics-java/blob/master/analytics/src/main/java/com/segment/analytics/Analytics.java#L121-L128. You can use this PR as an example and use  https://github.com/JakeWharton/retrofit1-okhttp3-client as your adapter.

**Comment by greenkiwi** [comment]
@f2prateek Thanks for merging this in.  When is the next release planned?

**Comment by f2prateek** [comment]
It might be a while, we generally release after we've seen some use out of the snapshot builds (https://github.com/segmentio/analytics-java/blob/master/README.md#snapshots). I'd recommend using the snapshots or https://github.com/segmentio/analytics-java/pull/108#issuecomment-344152391 until then.

**Comment by greenkiwi** [comment]
I'll shift over to snapshots.  Is there a way to know when new snapshots
are build?  And is the snapshot dot version incremented with each build?

**Comment by f2prateek** [comment]
All changes committed to master are automatically released as snapshots. Github might have a feed to track when there's a push to master.

The version stays the same until a release is made.

**Pull request merged**
