### PR TITLE
made segment endpoint configurable for isolated integration tests aga…

### PR DESCRIPTION
**Pull request by derarmin**
…inst a mockserver and not segment itself

### CODE REVIEW

**Comment by f2prateek** [comment]
Can you explain your use case? Why not just stub the client behind an interface or use something like mockito?

**Comment by derarmin** [comment]
Hey @f2prateek I am looking for a way to run integration tests against a mockserver, which is able to validate requests. This means in the case of integration test, I override the segment url with my mockservers and then ask my mockserver, if he gots a request.

**Comment by f2prateek** [comment]
My worry is that this is is overly configurable and encourages you to test the library internals instead of your application code. Testing that a `track` call makes it to the web server is the library's responsibility.

**Comment by derarmin** [comment]
For me it is more or less like that my application/service under test is getting event A with data and is sending a segment event with transformed/enriched data to my mockserver and lets me verify the data. The integration test sees my application/segment library as blackbox. If the application sends the data to segment I cant make sure, that the data is correct and everything works as expected.

**Comment by f2prateek** [comment]
Hmm... I'm still not sure why you couldn't test with a mock that your application calls the analytics class with the correct enriched data?

**Comment by derarmin** [comment]
The idea is to mock everything around my service and not inside or parts of it. All the services around can in be mocked by one mockserver. In the test I can verify the interaction with the mockserver. Thats all.

**Comment by derarmin** [comment]
I can live with my forked version

**Pull request closed without merging**
